version: 0.2

phases:
  pre_build:
    commands:
      # Login to Amazon ECR
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      # Building the image 
      - echo Building image...
      - docker compose -f docker-compose-build.yml build
      # Tag build
      - docker tag fitflow-gw:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/fitflow-gw:latest
      - docker tag fitflow-signup:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/fitflow-signup:latest
      - docker tag fitflow-subscription:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/fitflow-subscription:latest
  post_build:
    commands:
      # Publish image to ECR
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/fitflow-gw:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/fitflow-signup:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/fitflow-subscription:latest

artifacts:
  files:
    - 'docker-compose.yml'
  name: fitflow-production-artifacts