services:
  fitflow-gw:
    build:
      context: ./fitflow-gw
      tags:
        - fitflow-gw:latest
    ports:
      - "80:${GW_PORT}"
    depends_on:
      - signup
      - subscription
    environment:
      - GW_PORT=${GW_PORT}
      - SIGNUP_HOST=${SIGNUP_HOST}
      - SIGNUP_PORT=${SIGNUP_PORT}
      - SUBSCRIPTION_HOST=${SUBSCRIPTION_HOST}
      - SUBSCRIPTION_PORT=${SUBSCRIPTION_PORT}

  signup:
    build: 
      context: ./fitflow-signup
      tags:
        - fitflow-signup:latest
    ports:
      - "${SIGNUP_PORT}:${SIGNUP_PORT}"
    environment:
      - SIGNUP_HOST=${SIGNUP_HOST}
      - SIGNUP_PORT=${SIGNUP_PORT}
      - DB_HOST=${SIGNUP_DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_SIGNUP_NAME}

  subscription:
    build: 
      context: ./fitflow-subscription
      tags:
        - fitflow-subscription:latest
    ports:
      - "${SUBSCRIPTION_PORT}:${SUBSCRIPTION_PORT}"
    environment:
      - SIGNUP_HOST=${SIGNUP_HOST}
      - SIGNUP_PORT=${SIGNUP_PORT}
      - SUBSCRIPTION_HOST=${SUBSCRIPTION_HOST}
      - SUBSCRIPTION_PORT=${SUBSCRIPTION_PORT}
      - DB_HOST=${SUBSCRIPTION_DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_SUBSCRIPTION_NAME}
