services:
  api-gateway:
    build: ./fitflow-gw
    ports:
      - "${GW_PORT}:${GW_PORT}"
    depends_on:
      - signup
      - subscription
      - signup-database
      - subscription-database
    environment:
      - GW_PORT=${GW_PORT}
      - SIGNUP_HOST=${SIGNUP_HOST}
      - SIGNUP_PORT=${SIGNUP_PORT}
      - SUBSCRIPTION_HOST=${SUBSCRIPTION_HOST}
      - SUBSCRIPTION_PORT=${SUBSCRIPTION_PORT}

  signup:
    build: ./fitflow-signup
    ports:
      - "${SIGNUP_PORT}:${SIGNUP_PORT}"
    depends_on:
      - signup-database
    environment:
      - SIGNUP_HOST=${SIGNUP_HOST}
      - SIGNUP_PORT=${SIGNUP_PORT}
      - DB_HOST=${SIGNUP_DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_SIGNUP_NAME}

  signup-database:
    image: postgres
    ports:
      - "5433:${DB_PORT}"
    volumes:
      - "signup-database:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_SIGNUP_NAME}

  subscription:
    build: ./fitflow-subscription
    ports:
      - "${SUBSCRIPTION_PORT}:${SUBSCRIPTION_PORT}"
    depends_on:
      - signup
      - subscription-database
    environment:
      - SIGNUP_HOST=${SIGNUP_HOST}
      - SIGNUP_PORT=${SIGNUP_PORT}
      - SUBSCRIPTION_HOST=${SUBSCRIPTION_HOST}
      - SUBSCRIPTION_PORT=${SUBSCRIPTION_PORT}
      - DB_HOST=${SUBSCRIPTION_DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_SUBSCRIPTION_NAME}

  subscription-database:
    image: postgres
    ports:
      - "5434:${DB_PORT}"
    volumes:
      - "subscription-database:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_SUBSCRIPTION_NAME}

volumes:
  signup-database:
  subscription-database: